name: CI/CD counter app

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.AWS_USERNAME  }}
            REPO: portfolioaws
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker login
            docker pull ${{secrets.DOCKER_USER}}/$REPO
            docker stop portfolio
            docker rm portfolio
            docker run --detach --name portfolio -p 3000:3000 ${{secrets.DOCKER_USER}}/$REPO
