name: CI/CD counter app

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.AWS_USERNAME  }}
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker login
            echo "Successfully logged in"
            docker pull ${{secrets.DOCKER_USER}}/portfolioaws
            
            echo "pulled it"
            docker images
            docker ps
            
            docker stop portfolio
            
            echo "stopped"
            docker rm portfolio
            
            echo "removed container"
            docker ps
            
            docker run --detach --name portfolio -p 3000:3000 ${{secrets.DOCKER_USER}}/portfolioaws
